screenshots:
	./9h41m.sh

	convert +append DatePicker-*               -background transparent -splice 8x0+0+0 +append -chop 8x0+0+0 DatePicker.png
	convert +append DatePicker_date-*          -background transparent -splice 8x0+0+0 +append -chop 8x0+0+0 DatePicker_date.png
	convert +append DatePicker_hourAndMinute-* -background transparent -splice 8x0+0+0 +append -chop 8x0+0+0 DatePicker_hourAndMinute.png

	convert +append DatePicker_optional-*               -background transparent -splice 8x0+0+0 +append -chop 8x0+0+0 DatePicker_optional.png
	convert +append DatePicker_date_optional-*          -background transparent -splice 8x0+0+0 +append -chop 8x0+0+0 DatePicker_date_optional.png
	convert +append DatePicker_hourAndMinute_optional-* -background transparent -splice 8x0+0+0 +append -chop 8x0+0+0 DatePicker_hourAndMinute_optional.png
