screenshots:
	./10h09m.sh
	convert +append DatePicker-* -background transparent -splice 2x0+0+0 +append -chop 2x0+0+0 DatePicker.png
	convert +append DatePicker_date-* -background transparent -splice 2x0+0+0 +append -chop 2x0+0+0 DatePicker_date.png
	convert +append DatePicker_hourAndMinute-* -background transparent -splice 2x0+0+0 +append -chop 2x0+0+0 DatePicker_hourAndMinute.png
