capture:
	pushd ../Examples
	xcodebuild test -scheme 'Examples WatchKit App' -destination 'platform=watchOS Simulator,OS=9.1,name=Apple Watch Series 6 (40mm)'
	xcodebuild test -scheme 'Examples WatchKit App' -destination 'platform=watchOS Simulator,OS=9.1,name=Apple Watch Series 6 (44mm)'
	xcodebuild test -scheme 'Examples WatchKit App' -destination 'platform=watchOS Simulator,OS=9.1,name=Apple Watch Series 8 (41mm)'
	xcodebuild test -scheme 'Examples WatchKit App' -destination 'platform=watchOS Simulator,OS=9.1,name=Apple Watch Series 8 (45mm)'
	xcodebuild test -scheme 'Examples WatchKit App' -destination 'platform=watchOS Simulator,OS=9.1,name=Apple Watch Ultra (49mm)'
	popd
